// Test file to verify user's exact workflow structure renders correctly
import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import '@testing-library/jest-dom';
import WorkflowStepTreeCompact from '@/app/components/WorkflowStepTreeCompact';
import { WorkflowStep } from '@/app/types/workflow';

/**
 * This test verifies that the exact workflow structure generated by the LLM
 * renders correctly in the WorkflowStepTreeCompact component.
 * 
 * User reported: Browser console shows complete 5-step workflow, but Step Tree Pane
 * only displays 2-3 steps (inline onSuccess/onFailure branches not showing).
 */
describe('User Workflow Rendering - OR Logic with Inline Steps', () => {
  it('should render complete 5-step workflow with inline onSuccess/onFailure branches', () => {
    // Exact structure from user's generated workflow
    const steps: WorkflowStep[] = [
      {
        id: 'mrfSubmissionTrigger',
        name: 'Start: On MRF Submission',
        type: 'trigger',
        action: 'onMRFSubmit',
        params: { mrfTemplateName: 'all' },
        children: [
          {
            id: 'checkLocationOrAttendees',
            name: 'Check: Location Not US OR Attendees Over 100',
            type: 'condition',
            condition: {
              any: [
                { fact: 'mrf.location', operator: 'notEqual', value: 'US' },
                { fact: 'mrf.maxAttendees', operator: 'greaterThan', value: 100 }
              ]
            },
            onSuccess: {
              id: 'requestManagerApproval',
              name: 'Action: Request Manager Approval',
              type: 'action',
              action: 'requestApproval',
              params: { to: 'manager@example.com', message: 'Event requires approval' }
            },
            onFailure: {
              id: 'createEventAction',
              name: 'Action: Create Event',
              type: 'action',
              action: 'createEvent',
              params: { mrfID: 'dynamic' }
            }
          }
        ]
      },
      {
        id: 'workflowEnd',
        name: 'End: Workflow Complete',
        type: 'end',
        action: 'terminateWorkflow',
        params: { result: 'success' }
      }
    ];

    const { container } = render(<WorkflowStepTreeCompact steps={steps} />);

    // Step 1: Root trigger (mrfSubmissionTrigger)
    expect(screen.getByText('Start: On MRF Submission')).toBeInTheDocument();

    // Step 2: Root end step (workflowEnd)
    expect(screen.getByText('End: Workflow Complete')).toBeInTheDocument();

    // Expand the trigger step to see its children
    const triggerAccordion = screen.getByText('Start: On MRF Submission').closest('.MuiAccordionSummary-root');
    if (triggerAccordion) {
      fireEvent.click(triggerAccordion);
    }

    // Step 1.1: Condition step (checkLocationOrAttendees)
    // IMPORTANT: Condition steps with inline branches should be EXPANDED BY DEFAULT
    expect(screen.getByText('Check: Location Not US OR Attendees Over 100')).toBeInTheDocument();

    // Step 1.1.1: Inline onSuccess (requestManagerApproval)
    // This should now be VISIBLE WITHOUT manually expanding (auto-expanded)
    expect(screen.getByText('Action: Request Manager Approval')).toBeInTheDocument();

    // Step 1.1.2: Inline onFailure (createEventAction)
    // This should also be VISIBLE (auto-expanded)
    expect(screen.getByText('Action: Create Event')).toBeInTheDocument();

    // Verify all 5 steps are rendered
    const allText = container.textContent || '';
    console.log('Rendered content:', allText);

    // Count expected step names
    const expectedSteps = [
      'Start: On MRF Submission',              // 1
      'Check: Location Not US OR Attendees Over 100', // 1.1
      'Action: Request Manager Approval',      // 1.1.1 (inline onSuccess)
      'Action: Create Event',                  // 1.1.2 (inline onFailure)
      'End: Workflow Complete'                 // 2
    ];

    expectedSteps.forEach(stepName => {
      expect(allText).toContain(stepName);
    });
  });

  it('should render correct tree numbering for nested inline steps', () => {
    const steps: WorkflowStep[] = [
      {
        id: 'mrfSubmissionTrigger',
        name: 'Start: On MRF Submission',
        type: 'trigger',
        action: 'onMRFSubmit',
        params: {},
        children: [
          {
            id: 'checkLocationOrAttendees',
            name: 'Check: Location Not US OR Attendees Over 100',
            type: 'condition',
            condition: { any: [] },
            onSuccess: {
              id: 'requestManagerApproval',
              name: 'Action: Request Manager Approval',
              type: 'action',
              action: 'requestApproval',
              params: {}
            },
            onFailure: {
              id: 'createEventAction',
              name: 'Action: Create Event',
              type: 'action',
              action: 'createEvent',
              params: {}
            }
          }
        ]
      }
    ];

    const { container } = render(<WorkflowStepTreeCompact steps={steps} />);

    // Expand all accordions
    const accordions = container.querySelectorAll('.MuiAccordionSummary-root');
    accordions.forEach(accordion => fireEvent.click(accordion));

    // Verify numbering
    const text = container.textContent || '';
    expect(text).toContain('1.'); // Root trigger
    expect(text).toContain('1.1.'); // Child condition
    expect(text).toContain('1.1.1.'); // Inline onSuccess
    expect(text).toContain('1.1.2.'); // Inline onFailure
  });

  it('should show badge with nested step count when trigger step is collapsed', () => {
    const steps: WorkflowStep[] = [
      {
        id: 'mrfSubmissionTrigger',
        name: 'Start: On MRF Submission',
        type: 'trigger',
        action: 'onMRFSubmit',
        params: {},
        children: [
          {
            id: 'checkLocationOrAttendees',
            name: 'Check: Location Not US OR Attendees Over 100',
            type: 'condition',
            condition: { any: [] },
            onSuccess: {
              id: 'requestManagerApproval',
              name: 'Action: Request Manager Approval',
              type: 'action',
              action: 'requestApproval',
              params: {}
            },
            onFailure: {
              id: 'createEventAction',
              name: 'Action: Create Event',
              type: 'action',
              action: 'createEvent',
              params: {}
            }
          }
        ]
      }
    ];

    render(<WorkflowStepTreeCompact steps={steps} />);

    // Trigger step has 1 child, so badge should show "1 nested step"
    expect(screen.getByText('1 nested step')).toBeInTheDocument();
    
    // Expand the trigger step
    const triggerAccordion = screen.getByText('Start: On MRF Submission').closest('.MuiAccordionSummary-root');
    if (triggerAccordion) {
      fireEvent.click(triggerAccordion);
    }

    // Badge should disappear when expanded
    expect(screen.queryByText('1 nested step')).not.toBeInTheDocument();
  });

  it('should NOT show badge when condition step with inline branches is expanded by default', () => {
    const steps: WorkflowStep[] = [
      {
        id: 'checkBudget',
        name: 'Check: Budget Exceeds $10K',
        type: 'condition',
        condition: { all: [] },
        onSuccess: {
          id: 'requestApproval',
          name: 'Action: Request Manager Approval',
          type: 'action',
          action: 'requestApproval',
          params: {}
        },
        onFailure: {
          id: 'autoApprove',
          name: 'Action: Auto Approve',
          type: 'action',
          action: 'autoApprove',
          params: {}
        }
      }
    ];

    render(<WorkflowStepTreeCompact steps={steps} />);

    // Condition step should be expanded by default, so no badge
    expect(screen.queryByText('2 nested steps')).not.toBeInTheDocument();
    
    // But the inline steps should be visible
    expect(screen.getByText('Action: Request Manager Approval')).toBeInTheDocument();
    expect(screen.getByText('Action: Auto Approve')).toBeInTheDocument();
    
    // Now collapse the condition step
    const conditionAccordion = screen.getByText('Check: Budget Exceeds $10K').closest('.MuiAccordionSummary-root');
    if (conditionAccordion) {
      fireEvent.click(conditionAccordion);
    }

    // Badge should now appear
    expect(screen.getByText('2 nested steps')).toBeInTheDocument();
  });
});
