#!/bin/bash

##############################################################################
# Nginx Management Script
#
# Unified entry point for Nginx reverse proxy management
# Usage: npm run nginx [command]
#
# This script provides:
# - Container management (start, stop, restart, status)
# - Health checks and diagnostics
# - Logs and debugging
# - Configuration and help information
##############################################################################

set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCKER_COMPOSE_FILE="${SCRIPT_DIR}/docker-compose.yml"
CONTAINER_NAME="groupize-workflows-nginx"
NGINX_CERTS_DIR="${SCRIPT_DIR}/certs"
CERT_PATH="${NGINX_CERTS_DIR}/testing.app.groupize.com+2.pem"
KEY_PATH="${NGINX_CERTS_DIR}/testing.app.groupize.com+2-key.pem"

##############################################################################
# Helper Functions
##############################################################################

print_header() {
  echo -e "\n${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
  echo -e "${BLUE}║${NC} $1"
  echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}\n"
}

print_subheader() {
  echo -e "\n${CYAN}▸ $1${NC}\n"
}

print_success() {
  echo -e "${GREEN}✓${NC} $1"
}

print_error() {
  echo -e "${RED}✗${NC} $1"
}

print_warning() {
  echo -e "${YELLOW}⚠${NC} $1"
}

print_info() {
  echo -e "${CYAN}ℹ${NC} $1"
}

print_code() {
  echo -e "${CYAN}  $1${NC}"
}

##############################################################################
# Validation Functions
##############################################################################

check_docker() {
  if ! docker info > /dev/null 2>&1; then
    print_error "Docker is not running"
    echo ""
    print_info "Please start Docker Desktop and try again"
    exit 1
  fi
}

check_certificates() {
  if [ ! -f "$CERT_PATH" ] || [ ! -f "$KEY_PATH" ]; then
    print_warning "SSL certificates not found in $NGINX_CERTS_DIR"
    echo ""
    print_info "Did you run 'npm run setup' yet?"
    print_info "Run: npm run setup"
    echo ""
    print_error "Certificates must be generated by setup script first"
    exit 1
  fi
}

##############################################################################
# Core Commands
##############################################################################

cmd_start() {
  print_header "Starting Nginx Reverse Proxy"
  
  check_docker
  check_certificates
  
  cd "$SCRIPT_DIR"
  
  if docker ps | grep -q "$CONTAINER_NAME"; then
    print_warning "Container is already running"
    cmd_status
    return 0
  fi
  
  print_info "Building Docker image..."
  docker-compose build --no-cache
  
  echo ""
  print_info "Starting container..."
  docker-compose up -d
  
  echo ""
  print_success "Nginx container started successfully!"
  
  echo ""
  print_subheader "Access Points"
  print_code "Next.js app:        https://testing.app.groupize.com/aime"
  print_code "Testing environment: https://testing.app.groupize.com"
  print_code "Health check:       https://testing.app.groupize.com/health"
  
  echo ""
  print_subheader "Useful Commands"
  print_code "npm run nginx:stop   - Stop container"
  print_code "npm run nginx:logs   - View logs"
  print_code "npm run nginx status - Container status"
  echo ""
}

cmd_stop() {
  print_header "Stopping Nginx Reverse Proxy"
  
  check_docker
  
  cd "$SCRIPT_DIR"
  
  if ! docker-compose ps 2>/dev/null | grep -q "$CONTAINER_NAME"; then
    print_warning "Container is not running"
    return 0
  fi
  
  print_info "Stopping container..."
  docker-compose down
  
  echo ""
  print_success "Container stopped successfully"
  
  echo ""
  print_subheader "Next Steps"
  print_code "npm run nginx      - Start container again"
  print_code "npm run nginx logs - View logs"
  echo ""
}

cmd_logs() {
  print_header "Nginx Container Logs"
  
  check_docker
  
  cd "$SCRIPT_DIR"
  
  if ! docker-compose ps 2>/dev/null | grep -q "$CONTAINER_NAME"; then
    print_error "Container is not running"
    echo ""
    print_info "Start container with: npm run nginx"
    exit 1
  fi
  
  echo -e "${CYAN}Streaming logs (Ctrl+C to exit)...${NC}\n"
  docker-compose logs -f nginx
}

cmd_status() {
  print_header "Container Status"
  
  check_docker
  
  cd "$SCRIPT_DIR"
  
  echo "Docker Compose Status:"
  echo ""
  docker-compose ps
  
  echo ""
  if docker ps | grep -q "$CONTAINER_NAME"; then
    print_success "Nginx container is running"
    
    echo ""
    print_subheader "Container Details"
    docker inspect "$CONTAINER_NAME" | grep -E '"State"|"Status"|"Image"|"Ports"' | head -10
  else
    print_warning "Nginx container is not running"
  fi
  
  echo ""
}

cmd_restart() {
  print_header "Restarting Nginx Reverse Proxy"
  
  check_docker
  
  cd "$SCRIPT_DIR"
  
  print_info "Restarting container..."
  docker-compose restart nginx
  
  echo ""
  print_success "Container restarted successfully"
  
  sleep 2
  cmd_status
  echo ""
}

cmd_health() {
  print_header "Health Check"
  
  check_docker
  
  if ! docker ps | grep -q "$CONTAINER_NAME"; then
    print_error "Container is not running"
    echo ""
    print_info "Start container with: npm run nginx"
    exit 1
  fi
  
  print_info "Checking Nginx health..."
  echo ""
  
  if docker-compose -f "$DOCKER_COMPOSE_FILE" exec -T nginx wget --no-verbose --tries=1 --spider http://localhost/health 2>/dev/null; then
    echo ""
    print_success "Nginx is healthy"
  else
    print_error "Nginx health check failed"
    exit 1
  fi
  
  echo ""
}

cmd_help() {
  print_header "Nginx Reverse Proxy Management"
  
  echo -e "${CYAN}USAGE${NC}"
  print_code "npm run nginx [command]"
  
  echo ""
  echo -e "${CYAN}COMMANDS${NC}"
  print_code "start              Start the Nginx container (default)"
  print_code "stop               Stop the Nginx container"
  print_code "restart            Restart the Nginx container"
  print_code "status             Show container status"
  print_code "logs               Stream container logs"
  print_code "health             Check container health"
  print_code "help               Show this help message"
  
  echo ""
  echo -e "${CYAN}EXAMPLES${NC}"
  print_code "npm run nginx              # Start container"
  print_code "npm run nginx stop         # Stop container"
  print_code "npm run nginx logs         # View logs"
  
  echo ""
  echo -e "${CYAN}PREREQUISITES${NC}"
  print_code "✓ Docker Desktop running"
  print_code "✓ /etc/hosts entry: 127.0.0.1 testing.app.groupize.com"
  print_code "✓ Certificates auto-generated on first start (browser-trusted via mkcert)"
  
  echo ""
  echo -e "${CYAN}SETUP${NC}"
  print_code "npm run setup        # Setup /etc/hosts and generate certificates"
  print_code "npm run nginx        # Start container"
  
  echo ""
}

##############################################################################
# Main
##############################################################################

COMMAND="${1:-start}"

case "$COMMAND" in
  start)
    cmd_start
    ;;
  stop)
    cmd_stop
    ;;
  restart)
    cmd_restart
    ;;
  status)
    cmd_status
    ;;
  logs)
    cmd_logs
    ;;
  health)
    cmd_health
    ;;
  help)
    cmd_help
    ;;
  *)
    print_error "Unknown command: $COMMAND"
    echo ""
    cmd_help
    exit 1
    ;;
esac

