// src/app/utils/template-name-generator.ts
import ShortUniqueId from 'short-unique-id';

/**
 * Utility for generating unique template names
 */

const uid = new ShortUniqueId({ 
  length: 8,
  dictionary: 'alphanum_lower' // Only lowercase alphanumeric for clean URLs
});

/**
 * Generate a unique template name for new workflows
 * Format: "wf-{8-char-unique-id}"
 */
export function generateUniqueTemplateName(): string {
  return `wf-${uid.rnd()}`;
}

/**
 * Check if a template name appears to be auto-generated
 */
export function isAutoGeneratedTemplateName(name: string): boolean {
  return /^wf-[a-z0-9]{8}$/.test(name);
}

/**
 * Validate template name format
 */
export function isValidTemplateName(name: string): boolean {
  // Template names should be URL-safe and reasonable length
  return /^[a-zA-Z0-9\-_]{1,50}$/.test(name) && name.length >= 3;
}

/**
 * Sanitize a user-provided name to make it template-name safe
 */
export function sanitizeTemplateName(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9\-_]/g, '-') // Replace invalid chars with hyphens
    .replace(/-+/g, '-') // Collapse multiple hyphens
    .replace(/^-|-$/g, '') // Remove leading/trailing hyphens
    .substring(0, 50); // Limit length
}